#!/bin/bash

# Assuming the process ID (PID) of 4-to_infinity_and_beyond is stored in a file
# named pidfile.txt. Adjust this if your setup is different.

while read -r pid; do
  echo "Stopping process $pid"
  # Sending a SIGSTOP signal to pause the process
  kill -STOP "$pid"
  sleep 2
  # Sending a SIGCONT signal to resume the process
  kill -CONT "$pid"
done < pidfile.txt

